### ISSUE TITLE
Cell Key Method - Error in y$is_rootnode : $ operator is invalid for atomic vectors

### ISSUE THREAD

**Issue by vanessa-azzopardi-work** [sdcTools/cellKey#15] opened 2023-09-17 10:22 UTC
Hi,

I'm trying out the Cell Key Method using the R packages cellKey and sdcHierarchies by following the documentation (https://sdctools.github.io/cellKey/articles/introduction.html).  I encountered the following error when running the command:

```
hc_1.1 <- cellKey::ck_setup(x = data,
                   rkey = "r_keys",
                   dims = dims,
                   w = NULL)
```

![Capture](https://github.com/sdcTools/cellKey/assets/75853527/62f31ff1-88f9-4e40-84d9-3e2192b83f99)

I tried debugging using: `debug(ck_setup)` but was unable to reach the lines where the error is being generated.  There was a warning saying 'Debug location is approximate because the source is not available'.

Am I missing something?  @bernhard-da  @tenderle any help would be appreciated :)  I am attaching the workspace image and R script for reference.  Since I cannot provide the microdata, I am providing the output to `str(data)`:

![Capture_3](https://github.com/sdcTools/cellKey/assets/75853527/30bc8f24-c8f2-4e4a-b3a1-ab024aa1712a)

I am using the following package versions:

![Capture_2](https://github.com/sdcTools/cellKey/assets/75853527/ede55389-56ed-4157-be53-4467570e6383)

[CKM_RScript_WorkspaceImage.zip](https://github.com/sdcTools/cellKey/files/12642559/CKM_RScript_WorkspaceImage.zip)

**Comment by bernhard-da** [comment] 2023-09-17 12:05
@vanessa-azzopardi thx for reporting the issue. I will have a look at it early next week.

**Comment by bernhard-da** [comment] 2023-09-19 06:26
@vanessa-azzopardi I think the problem is that you are specifying `GEO.N` which is not really a dimension (only one subtotal contributing to a "pseudo"-total. If you omit this hierarchy
```
dims$GEO.N <- NULL
cellKey::ck_setup(
  x = data,
  rkey = "r_keys",
  dims = dims
)
```
everything works; I have however made a possible update in https://github.com/sdcTools/cellKey/commit/25eeae666e2a141eb5a46917ba7c48dc0e58e1d6 and it would be good, if you could confirm, that it is working with this version. You can download a pre-built version for windows [here](https://win-builder.r-project.org/q4cVo1s3aGCx/cellKey_1.0.1.zip) (available for the next ~72hours) or install using
```
remotes::install_github("sdcTools/cellKey", ref = "issue-15")
```
If this works, I will make a new version for CRAN soon.

**Comment by vanessa-azzopardi-work** [comment] 2023-09-19 07:10
Many thanks for your help @bernhard-da 

I installed the updated version of the package but I am facing the same issue when using GEO.N.  However, as you said, everything works fine when I omit GEO.N.

![image](https://github.com/sdcTools/cellKey/assets/75853527/cdd63605-4e17-4b15-b426-90be9111a869)

**Comment by bernhard-da** [comment] 2023-09-19 10:50
@vanessa-azzopardi thx for the reply; Could you please double-check if the updated version of the package was indeed loaded? I did not change the version number, so unfortunately it is a bit difficult to see. But please make sure that you restarted your R-Session before loading the newly-installed package. Because when I tried, I received no error using the following  testdata and the `dims` object your provided.
```
N <- 1000
data <- data.frame(
  r_keys = runif(N),
  LMS = sample(c(100, 200, 300, 400), N, replace = TRUE),
  GEO.N = 1,
  SEX = sample(1:2, N, replace = TRUE),
  AGE.H = sample(c(
               "111", "112", "113", "114", "115", "121",
               "122", "123", "124", "125", "131", "132",
               "133", "134", "135", "211", "212", "213",
               "214", "215", "221", "222", "223", "224",
               "225", "231", "232", "233", "234", "235",
               "311", "312", "313", "314", "315", "321",
               "322", "323", "324", "325", "331", "332",
               "333", "334", "335", "341", "342", "343",
               "344", "345", "411", "412", "413", "414",
               "415", "421", "422", "423", "424", "425",
               "431", "432", "433", "434", "435", "511",
               "512", "513", "514", "515", "521", "522",
               "523", "524", "525", "531", "532", "533",
               "534", "535", "541", "542", "543", "544",
               "545", "611", "612", "613", "614", "615",
               "621", "622", "623", "624", "625", "631",
﻿               "632", "633", "634", "635", "640"), N, replace = TRUE)
)

p1 <- cellKey::ck_setup(
  x = data,
  rkey = "r_keys",
  dims = dims,
  w = NULL
)
```
So please could you do me a favor and test again? That would be great. Thx

**Comment by vanessa-azzopardi-work** [comment] 2023-09-19 11:01
@bernhard-da sorry about that, it seems I had the original version loaded.  Restarting the session did the trick :)

Everything works fine now, even when GEO.N is used.  Thank you so much for your help and prompt fix!  Much appreciated

**Comment by bernhard-da** [comment] 2023-09-19 11:36
@vanessa-azzopardi thx for the promt test and confirmation that everything works; I have merged the fix and will make a new version for CRAN soon.

**Closed as completed by bernhard-da** 2023-09-19 11:36 UTC
Labels: bug
