### ISSUE TITLE
Consistent perturbation

### ISSUE THREAD

**Issue by tenderle** [sdcTools/cellKey#3] opened 2018-06-19 08:15 UTC
Hi @bernhard-da, 

attached you will find a short example of the perturbation tests on consistency we did. I produced several results using the data set `dat <- dat[,c("sex","age","income"),]`.

I ran the perturbation four times. On the one hand, I distinguished between a complete data set `dat1 <- dat` and a reduced data set `dat2 <- dat[income>0,,]`. Then, I compared the built-in key generation (a) `ck_create_input(..., def_rkey=9, ...)` vs. (b) pre-drawn keys `ck_create_input(..., def_rkey="rkeys_predrawn",...)`.

Now we have the following two issues:
- **Perturbation of frequencies**: When removing units from the data, the built-in key generation results in different cell keys and, hence, different perturbation for unaffected frequencies (compare `res_destatis_1a@tab` with `res_destatis_2a@tab`). However, if we use externally pre-drawn record key option of your function, we get consistent perturbations (compare `res_destatis_1b@tab` with `res_destatis_2b@tab`).

- **Perturbation of continuous variables**: As Sarah mentioned in her mail, the ABS approach for continuous data produces some inconsistencies if a user removes units with zero contribution to a continuous variable (e.g. `income = 0`). Therefore, I removed the one unit (`sex==1 & age==3 & income==0`) and received `dat2`. Let's compare the column `income.pert` in `res_destatis_1a@tab` and `res_destatis_2a@tab` As expected (because of the abs approach), there are different cell keys and perturbed incomes for `sex==1 & age==3` as well as for higher aggregates.  However, there are also different cell keys and results for other cells such as `sex==1 & age==1`. In case of the externally pre-drawn record keys, we can also observe differences (but only for perturbed income not cell keys).

Is it possible to solve the issues? In case of the consistency issue for continuous variables - that may be also of interest for @ppdewolf - Sarah solved the issue within an destatis-internal prototype. She multiplied the original record key by a dichotomous indicator variable: 0=no contribution of the continuous variable (e.g. income=0) such that the cell key will be identical to the case that users exclude such units from the data set, and 1=otherwise. May that be a solution for both of you?

Best,
@tenderle

Here is the complete code:
```
# Cell Key
library(cellKey)

## The data set (sex, age, income)
dat <- ck_create_testdata()
dat <- dat[,c("sex","age","income"),]

dim.sex <- data.table(levels=c("@","@@","@@"), codes=c("Total", "male","female"))
dim.age <- data.table(levels=c("@",rep("@@", 6)), codes=c("Total", paste0("age_group",1:6)))
dimList <- list(sex=dim.sex, age=dim.age)
weightVar <- NULL
numVars <- c("income")

# parameters
pTable_destatis <- ck_create_pTable(type="destatis")
sTable <- ck_generate_sTable(smallC=12)
mTable <- c(0.6,0.4,0.2)

pert_params_destatis <- ck_create_pert_params(
  smallN=12,
  pTable=pTable_destatis,
  sTable=sTable,
  mTable=mTable)

# Externally predrawn record keys
set.seed(123)
dat$rkeys_predrawn <- round(runif(dim(dat)[1]), 9)

## Two data set ('dat1' with all individuals, and 'dat2' with those which have positive income)

# i.e. one unit will be excluded in dat2 (sex=1, age=3 and income=0)
dat[income==0,,]

dat1 <- dat
dat2 <- dat[income>0,,]

## (a) Both data sets using the implemted key generation
inp_destatis_1a <- ck_create_input(
  dat=dat1,
  def_rkey=9,
  pert_params=pert_params_destatis)

inp_destatis_2a <- ck_create_input(
  dat=dat2,
  def_rkey=9,
  pert_params=pert_params_destatis)

res_destatis_1a <- perturbTable(
  inp=inp_destatis_1a,
  dimList=dimList,
  weightVar=weightVar, numVars=numVars)

res_destatis_2a <- perturbTable(
  inp=inp_destatis_2a,
  dimList=dimList,
  weightVar=weightVar, numVars=numVars)


## (b) Both data sets using externally generated keys
inp_destatis_1b <- ck_create_input(
  dat=dat1,
  def_rkey="rkeys_predrawn",
  pert_params=pert_params_destatis)

inp_destatis_2b <- ck_create_input(
  dat=dat2,
  def_rkey="rkeys_predrawn",
  pert_params=pert_params_destatis)


res_destatis_1b <- perturbTable(
  inp=inp_destatis_1b,
  dimList=dimList,
  weightVar=weightVar, numVars=numVars)

res_destatis_2b <- perturbTable(
  inp=inp_destatis_2b,
  dimList=dimList,
  weightVar=weightVar, numVars=numVars)

## Results (a)
res_destatis_1a@tab[,cellKey:=res_destatis_1a@cellKeys,]
res_destatis_2a@tab[,cellKey:=res_destatis_2a@cellKeys,]

res_destatis_1a@tab
res_destatis_2a@tab

## Results (b)
res_destatis_1b@tab[,cellKey:=res_destatis_1b@cellKeys,]
res_destatis_2b@tab[,cellKey:=res_destatis_2b@cellKeys,]

res_destatis_1b@tab
res_destatis_2b@tab
```

**Comment by bernhard-da** [comment] 2018-06-19 13:00
hi @tenderle, thx for the tests and summarizing this issue.

my quick comments:

as for the perturbation of frequencies: i think the elegance of the method was always to use the same input data as starting point, defining keys and using the same input over and over again for different tabulations. this is possible as you've already described by adding a record key to the input data and re-using these record keys. one (easy) way to solve this, is that we internally generate record keys by group (eg. we split the data set depending on the hierarchical input (eg `dimList` in `perturbTable()`) and compute hashes for sub-groups. this would result only lead to different rkeys for groups, to which or from which units have been added/removed. the drawback of course is, that we need to do this for every call of `perturbTable()`. 

another comment: perhaps it would be easier to add an argument `countVars` similar to `numVars()` in which one can add a indicator variable which will be perturbed according to the count-algorithm. thus it would be easy possible to add a indicator variable that is 0 that should not be counted depending on values of other variables.

as for the second issue: I'll try to implement Sarah's approch for the next version. but perhaps also the "draw-rec-keys-by-group" approach might help here...

**Comment by tenderle** [comment] 2018-06-19 14:23
@bernhard-da thx for the quick reply. Ok, that is, as I can see, the current built-in approach is based upon the seed which initially is computed using the data driven hash. Each change in the data (i.e. adding/removing units and/or variables) results in a different seed and, hence, in different record keys.

However, there are situations where data sets must be changed. The easy approach you mentioned would result, as you mentioned, in group-based seeds or record keys. Thus, from my point of view, the option to use externally pre-drawn record keys seems to be an absolutely fair solution.

Then, there are these different results of `income.pert` when comparing `res_destatis_1a@tab` and `res_destatis_2a@tab`. For example in case of `sex==1`:
```
res_destatis_1b@tab[c(9:14),,]
res_destatis_2b@tab[c(9:14),,]
```
For the perturbation of continuous variables you don't use these pre-drawn record keys. Why don't we have differences for `sex==2`?
```
res_destatis_1b@tab[c(16:21),,]
res_destatis_2b@tab[c(16:21),,]
```
Does this happen by accident and maybe I should repeat it with different data. Or do you have an explanation?

**Comment by bernhard-da** [comment] 2018-06-19 14:40
@tenderle this is a bug I guess. I'll have a look into this. the difference (if any) in `income.pert` should be in group `male` x `age_group3`.

**Comment by tenderle** [comment] 2018-06-19 16:44
Ok, I just wondered why there are differences for some cells but not for `sex==1 & age==3`.

**Comment by bernhard-da** [comment] 2018-06-19 18:28
@tenderle i think the problem is in `get_row_index_cont()` and `get_col_index_cont()`. these two functions are based on the abs-way to specify record keys and map the record-keys of the topK contributing units per cell to the specified sTtable of 256 rows and smallC columns. what is the destatis-way of doing the mapping? 

also, there is a similar problem in `get_direction()`: an easy way to solve this would be to assign +1 all record keys >= 0.5 and -1 to all record keys having values <0.5. but for the former mentioned functions, there is no "easy" mapping. one possibility would be to (internally) recode destatis-rkeys to abs-rkeys using some function for the perturbation of numerical variables.

**Comment by bernhard-da** [comment] 2018-06-19 20:11
@tenderle i think i've fixed the bug in `perturbTable()` you described with commit 68f37400a665209b0df251707d013f971f755114. could you please check again?

```rm(list=ls())
library(cellKey)

dat <- ck_create_testdata()
dat <- dat[,c("sex","age","income"),]

dim.sex <- ck_create_node(total_lab="Total")
dim.sex <- ck_add_nodes(dim.sex, node_labs=c("male","female"), reference_node="Total")
dim.age <- ck_create_node(total_lab="Total")
dim.age <- ck_add_nodes(dim.age, node_labs=paste0("age_group",1:6), reference_node="Total")
dimList <- list(sex=dim.sex, age=dim.age)

pTable_destatis <- ck_create_pTable(type="destatis")
sTable <- ck_generate_sTable(smallC=12)
mTable <- c(0.6,0.4,0.2)

pert_params_destatis <- ck_create_pert_params(smallN=12, pTable=pTable_destatis, sTable=sTable, mTable=mTable)

# Externally predrawn record keys
set.seed(123)
dat$rkeys_predrawn <- round(runif(dim(dat)[1]), 9)

dat1 <- dat
dat2 <- dat[income>0,,]

inp_destatis_1b <- ck_create_input(dat=dat1, def_rkey="rkeys_predrawn", pert_params=pert_params_destatis)
inp_destatis_2b <- ck_create_input(dat=dat2, def_rkey="rkeys_predrawn", pert_params=pert_params_destatis)

res_destatis_1b <- perturbTable(inp=inp_destatis_1b, dimList=dimList, weightVar=NULL, numVars="income")
res_destatis_2b <- perturbTable(inp=inp_destatis_2b, dimList=dimList, weightVar=NULL, numVars="income")
res_destatis_1b@tab[,cellKey:=res_destatis_1b@cellKeys,]
res_destatis_2b@tab[,cellKey:=res_destatis_2b@cellKeys,];

# 1=total, 4=Total x age_group3, 8= male x Total, 11=male x age_group3
which(res_destatis_1b@tab[,cellKey] != res_destatis_2b@tab[, cellKey])
```

**Comment by tenderle** [comment] 2018-06-20 07:36
Good morning @bernhard-da. Nice, you fixed it before I was able to answer ;-) Without looking into the code, I reran the example and `which(res_destatis_1b@tab[,income.pert] != res_destatis_2b@tab[, income.pert])` suggests that I have the results I supposed to get (Edit: apart from the indicator approach as mentioned in the first post of this thread). When having time I will have a look how you have solved it. Thx

**Comment by bernhard-da** [comment] 2018-06-21 18:10
@tenderle if you have some spare time :) you could try out the new feature-branch i've just pushed (`install_github("sdcTools/cellKey", ref="improvements", build_vignettes=TRUE)`)

`perturbTable()` has gained a new argument `countVars` which optionally can take additional 0/1 coded variables. Thus it is suitable to compute consistent perturbed tables for any subgroups defined by the binary variables. For examples have a look at `?perturbTable()`

it would be great to get some feedback weather this is as useful as i think it is :)

**Comment by bernhard-da** [comment] 2018-06-22 06:28
@tenderle `perturbTable()` now has an additional argument `by` which addresses the second issue you mentioned. you could please test and report back so that i can merge this to master and close this issue? thx

**Comment by tenderle** [comment] 2018-06-22 08:14
@bernhard-da perfect, I will try to test them today ... just need some time, because I will always have to use a workaround and ther is no direct possibility to use install_github() within our IT facilities 

by the way, do you know or could you recommend a reliable web service with r-studio web interface that substitutes an own R installation and has the entire funcitonality (all necessary packages) to interact with github?

**Comment by bernhard-da** [comment] 2018-06-22 09:27
@tenderle what you can try is to download the snapshot and install it directly

```
install_ck_local <- function(branch="master") {
  stopifnot(branch %in% c("master"," improvements"))
  f <- tempfile(fileext = ".zip")
  u <- file.path("https://github.com/sdcTools/cellKey/archive", paste0(branch,".zip"))
  download.file(u, destfile = f)
  
  td <- tempdir()
  unzip(f, exdir=td, list=FALSE)
  file.remove(f)
  
  devtools::install(file.path(td,paste0("cellKey-",branch)))
}
install_ck_local(branch="improvements")
```

**Comment by tenderle** [comment] 2018-06-22 09:45
@bernhard-da thx, way better than my manual unzipping ;-) not thought about something like `unzip()`

however, still looking for an alternative way for managing our ptable package (pushing/pulling) ... maybe the technical issues will be solved within next week

**Comment by tenderle** [comment] 2018-06-22 11:16
@bernhard-da I installed your improvement-branch and did some first checks. Of course, the new features seem to be very useful ... especially the `by` argument.

However, before I could do some more reliable tests there may be a bug I want to report. Before applying the count variables using `countVars` (i.e. `=NULL`) I got no numerical results for females. If you run `ck_cont_table(res_destatis, vname="income", meanBeforeSum=TRUE)` you can see it (by the way: the example in `?perturbTable` doesn't call the destatis result, it is always `res_abs`).

**Comment by bernhard-da** [comment] 2018-06-22 11:40
@tenderle thx for the feedback. i just pushed the correction for the examples.

for the other thing, could you please open another issue as it is easier to follow-on ... (and also with a reproducible example :) )

**Comment by tenderle** [comment] 2018-06-22 12:51
@bernhard-da Sorry, but I can't reproduce the bug after updating the package and restarting R (it was the result from running your example). Since you only updated the lines regarding the manuals, I have no glue what happened :-/ Anyway, now everything is fine (if I get the bug again I would open another issue; maybe it ocurred because I ran your code within my own R-Studio project). Nevertheless I may finish the testing next week and give my feedback then.

**Comment by tenderle** [comment] 2018-06-22 13:56
@bernhard-da Now I was able to reproduce a similar bug. I have posted it here: #4

**Comment by bernhard-da** [comment] 2018-07-06 09:11
@tenderle i'll close this for now. if you find another issue, just repopen this issue or create a new one.

**Closed as completed by bernhard-da** 2018-07-06 09:11 UTC
Labels: enhancement, question, awaiting_feedback
